# Postgres for the CommonTrace Hub on Google Cloud: private IP only, TLS required, regional high
# availability, CMEK, and point-in-time recovery. It creates no Hub workload and no ingress; see
# deploy/helm/commontrace-hub. `terraform apply` creates billable resources: plan first.

resource "google_sql_database_instance" "this" {
  name                = var.name
  database_version    = "POSTGRES_16"
  region              = var.region
  deletion_protection = var.deletion_protection
  encryption_key_name = var.kms_key_name

  settings {
    tier                        = var.tier
    edition                     = "ENTERPRISE"
    availability_type           = var.high_availability ? "REGIONAL" : "ZONAL"
    disk_type                   = "PD_SSD"
    disk_size                   = var.disk_size_gb
    disk_autoresize             = true
    deletion_protection_enabled = var.deletion_protection

    ip_configuration {
      ipv4_enabled    = false
      private_network = var.network_self_link
      ssl_mode        = "ENCRYPTED_ONLY"
    }

    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
      start_time                     = "03:00"
      transaction_log_retention_days = var.backup_retention_days
      backup_retention_settings {
        retained_backups = var.backup_retention_days
        retention_unit   = "COUNT"
      }
    }

    database_flags {
      name  = "max_connections"
      value = tostring(var.max_connections)
    }
    database_flags {
      name  = "log_min_duration_statement"
      value = "500"
    }

    insights_config {
      query_insights_enabled = true
    }

    maintenance_window {
      day  = 7
      hour = 4
    }
  }
}

resource "google_sql_database" "hub" {
  name     = "commontrace_hub"
  instance = google_sql_database_instance.this.name
}

# The owner's password is generated by Cloud SQL tooling or your secret manager, never set here:
# a password in a variable ends up in state.
