apiVersion: v1
kind: Service
metadata:
  name: commontrace-hub
  labels:
    app: commontrace-hub
spec:
  type: ClusterIP
  selector:
    app: commontrace-hub
  ports:
    - name: http
      port: 8420
      targetPort: http
