apiVersion: v1
kind: Service
metadata:
  name: {{ include "hub.name" . }}
  labels: {{- include "hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "hub.name" . }}
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
