"""widen retrievals depth commons_hits counters to bigint

Revision ID: 40d3f29cbb24
Revises: 126ec57affb6
Create Date: 2026-08-23 03:34:19.895826

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40d3f29cbb24'
down_revision: Union[str, None] = '126ec57affb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # These are unbounded monotonic counters (never decremented, never
    # reset) on rows that can live for the life of a long-running Hub. A
    # 32-bit Integer caps out at ~2.1 billion; crossing that ceiling makes
    # Postgres raise "integer out of range" on the next
    # `UPDATE ... SET x = x + 1`, turning an ordinary read/query into an
    # unhandled 500 for every future call touching that row. ALTER COLUMN
    # ... TYPE bigint is a safe, non-data-loss widening (every existing
    # int4 value fits in an int8) -- Postgres still rewrites the table to
    # apply it, so on a very large `traces` table this briefly holds an
    # ACCESS EXCLUSIVE lock; run during a maintenance window on a
    # deployment where that matters.
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traces', 'retrievals',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('traces', 'depth',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('traces', 'commons_hits',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traces', 'commons_hits',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traces', 'depth',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('traces', 'retrievals',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
