"""plans: org plan column and usage counters

Adds the entitlement model (hub/plans.py): which plan an org is on, and a
shared, atomically-incremented usage meter so limits survive running more
than one Hub replica.

Both changes are additive and safe to apply while the previous version is
still serving: the old code never reads `organizations.plan` and never
touches `usage_counters`, and every existing org lands on the smallest
plan rather than an unlimited one.

Revision ID: 4e1e9ecbff1f
Revises: 3b6ef8cbb362
Create Date: 2026-08-21 02:41:53.743677

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e1e9ecbff1f'
down_revision: Union[str, None] = '3b6ef8cbb362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_counters',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('org_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'period', 'metric', name='uq_usage_org_period_metric')
    )
    op.create_index(op.f('ix_usage_counters_org_id'), 'usage_counters', ['org_id'], unique=False)
    # server_default is REQUIRED here and autogenerate does not emit it:
    # ADD COLUMN ... NOT NULL with no default fails outright on a table that
    # already has rows ("column \"plan\" of relation \"organizations\"
    # contains null values"), which is every production database this will
    # ever run against. Verified by attempting it without one.
    #
    # The default is 'free' and not a paid tier for the obvious reason: a
    # migration that silently upgrades every existing customer's
    # entitlements is a migration that gives the product away. Existing orgs
    # land on the smallest plan and an operator moves them with
    # `python -m hub.manage set-plan`.
    op.add_column(
        'organizations',
        sa.Column('plan', sa.String(length=32), nullable=False, server_default='free'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'plan')
    op.drop_index(op.f('ix_usage_counters_org_id'), table_name='usage_counters')
    op.drop_table('usage_counters')
    # ### end Alembic commands ###
