"""contribute_trace idempotency key

Revision ID: 5707b1fc15d3
Revises: a9237315f409
Create Date: 2026-08-20 12:17:12.546226

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5707b1fc15d3'
down_revision: Union[str, None] = 'a9237315f409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traces', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.add_column('traces', sa.Column('request_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_traces_org_idempotency_key', 'traces', ['org_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_traces_org_idempotency_key', 'traces', type_='unique')
    op.drop_column('traces', 'request_hash')
    op.drop_column('traces', 'idempotency_key')
    # ### end Alembic commands ###
