"""initial schema

Revision ID: b1e835b3302d
Revises:
Create Date: 2026-08-19 13:58:15.289771

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1e835b3302d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('org_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_table('traces',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('org_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('context_text', sa.Text(), nullable=False),
    sa.Column('solution_text', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('profile', sa.String(length=128), nullable=False),
    sa.Column('extensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('watch_condition', sa.Text(), nullable=False),
    sa.Column('review_after', sa.String(length=64), nullable=False),
    sa.Column('supersedes_trace_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('contributor', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trust', sa.Float(), nullable=False),
    sa.Column('retrievals', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.Column('quarantine_reason', sa.String(length=200), nullable=False),
    sa.Column('shared_with_commons', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_org_id'), 'traces', ['org_id'], unique=False)
    op.create_index('ix_traces_org_quarantined', 'traces', ['org_id', 'quarantined'], unique=False)
    op.create_index('ix_traces_tags_gin', 'traces', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('trace_relations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('related_trace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_relations_trace_id'), 'trace_relations', ['trace_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('org_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vote_type', sa.String(length=8), nullable=False),
    sa.Column('feedback_tag', sa.String(length=32), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint(
        "feedback_tag IN ('', 'outdated', 'wrong', 'security_concern', 'spam')", name='ck_votes_feedback_tag'
    ),
    sa.CheckConstraint("vote_type IN ('up', 'down')", name='ck_votes_vote_type'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id', 'org_id', name='uq_votes_trace_org')
    )
    op.create_index(op.f('ix_votes_org_id'), 'votes', ['org_id'], unique=False)
    op.create_index(op.f('ix_votes_trace_id'), 'votes', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_trace_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_org_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_trace_relations_trace_id'), table_name='trace_relations')
    op.drop_table('trace_relations')
    op.drop_index('ix_traces_tags_gin', table_name='traces', postgresql_using='gin')
    op.drop_index('ix_traces_org_quarantined', table_name='traces')
    op.drop_index(op.f('ix_traces_org_id'), table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('organizations')
    # ### end Alembic commands ###
